-- MySQL Script generated by MySQL Workbench
-- 11/11/16 15:59:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `test_sp_database` DEFAULT CHARACTER SET utf8 ;
USE `test_sp_database` ;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `real_name` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `note` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `referrer` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `referer_idx` (`referrer` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`sp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number` INT(3) NOT NULL,
  `percent` DECIMAL(4,2) NOT NULL DEFAULT '0.15',
  `status` INT(2) NOT NULL DEFAULT '1',
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `date_to_pay` DATE NOT NULL,
  `date_sent` DATE NULL DEFAULT NULL,
  `date_to_receive` DATE NULL DEFAULT NULL,
  `date_received` DATE NULL DEFAULT NULL,
  `date_to_distribute` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `client` INT(11) NOT NULL,
  `sp` INT(11) NOT NULL,
  `weight` INT(5) NOT NULL DEFAULT '0',
  `status` INT(1) NOT NULL DEFAULT '1',
  `prepaid` DECIMAL(7,2) NOT NULL DEFAULT '0.00',
  `note` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `date_ordered` DATE NOT NULL,
  `date_completed` DATE NULL DEFAULT NULL,
  `delivery_price` DECIMAL(7,2) NOT NULL,
  `place` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `status_idx` (`status` ASC),
  INDEX `place_to_complete_idx` (`place` ASC),
  INDEX `client_idx` (`client` ASC),
  INDEX `sp_idx` (`sp` ASC),
  CONSTRAINT `client`
    FOREIGN KEY (`client`)
    REFERENCES `test_sp_database`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sp`
    FOREIGN KEY (`sp`)
    REFERENCES `test_sp_database`.`sp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `price` DECIMAL(4,0) NOT NULL,
  `link` VARCHAR(300) NOT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  `vkid` INT(15) NULL DEFAULT NULL,
  `imagelink` VARCHAR(300) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `vkphotoid` INT(11) NULL DEFAULT NULL,
  `weight` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 928
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`order_position` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `price_ordered` DECIMAL(7,2) NOT NULL,
  `price_sp` DECIMAL(7,2) NOT NULL,
  `price_vendor` DECIMAL(7,2) NOT NULL,
  `quantity` INT(2) NOT NULL,
  `note` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id_idx` (`order_id` ASC),
  INDEX `product_idx` (`product_id` ASC),
  CONSTRAINT `order`
    FOREIGN KEY (`order_id`)
    REFERENCES `test_sp_database`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `test_sp_database`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `test_sp_database`.`properties` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `percent_sp` DECIMAL(4,2) NOT NULL,
  `percent_discount` DECIMAL(4,2) NOT NULL,
  `percent_bank_commission` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;